(cl:defpackage pkg_ros_actions-msg
  (:use )
  (:export
   "<MSGTURTLEACTION>"
   "MSGTURTLEACTION"
   "<MSGTURTLEACTIONFEEDBACK>"
   "MSGTURTLEACTIONFEEDBACK"
   "<MSGTURTLEACTIONGOAL>"
   "MSGTURTLEACTIONGOAL"
   "<MSGTURTLEACTIONRESULT>"
   "MSGTURTLEACTIONRESULT"
   "<MSGTURTLEFEEDBACK>"
   "MSGTURTLEFEEDBACK"
   "<MSGTURTLEGOAL>"
   "MSGTURTLEGOAL"
   "<MSGTURTLERESULT>"
   "MSGTURTLERESULT"
  ))

