// Generated by gencpp from file pkg_ros_iot_bridge/msgIotRosFeedback.msg
// DO NOT EDIT!


#ifndef PKG_ROS_IOT_BRIDGE_MESSAGE_MSGIOTROSFEEDBACK_H
#define PKG_ROS_IOT_BRIDGE_MESSAGE_MSGIOTROSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_ros_iot_bridge
{
template <class ContainerAllocator>
struct msgIotRosFeedback_
{
  typedef msgIotRosFeedback_<ContainerAllocator> Type;

  msgIotRosFeedback_()
    : percentage_complete(0)  {
    }
  msgIotRosFeedback_(const ContainerAllocator& _alloc)
    : percentage_complete(0)  {
  (void)_alloc;
    }



   typedef int8_t _percentage_complete_type;
  _percentage_complete_type percentage_complete;





  typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct msgIotRosFeedback_

typedef ::pkg_ros_iot_bridge::msgIotRosFeedback_<std::allocator<void> > msgIotRosFeedback;

typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgIotRosFeedback > msgIotRosFeedbackPtr;
typedef boost::shared_ptr< ::pkg_ros_iot_bridge::msgIotRosFeedback const> msgIotRosFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_ros_iot_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pkg_ros_iot_bridge': ['/home/avinash/catkin_ws/src/pkg_ros_iot_bridge/msg', '/home/avinash/catkin_ws/devel/.private/pkg_ros_iot_bridge/share/pkg_ros_iot_bridge/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5151973e38c593f60bed311537d61df";
  }

  static const char* value(const ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5151973e38c593fULL;
  static const uint64_t static_value2 = 0x60bed311537d61dfULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_ros_iot_bridge/msgIotRosFeedback";
  }

  static const char* value(const ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"int8 percentage_complete\n"
"\n"
;
  }

  static const char* value(const ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgIotRosFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_ros_iot_bridge::msgIotRosFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage_complete: ";
    Printer<int8_t>::stream(s, indent + "  ", v.percentage_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_ROS_IOT_BRIDGE_MESSAGE_MSGIOTROSFEEDBACK_H
